CREATE USER EDTOOL
  IDENTIFIED BY EDTOOL
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 32 Roles for EDTOOL 
GRANT CONNECT TO EDTOOL;
GRANT RESOURCE TO EDTOOL;
GRANT CREATE SEQUENCE TO EDTOOL;
GRANT CREATE SESSION TO EDTOOL;
GRANT CREATE SYNONYM TO EDTOOL;
GRANT CREATE TABLE TO EDTOOL;
GRANT CREATE TABLESPACE TO EDTOOL;
GRANT CREATE TRIGGER TO EDTOOL;
GRANT CREATE TYPE TO EDTOOL;
GRANT CREATE USER TO EDTOOL;
GRANT CREATE VIEW TO EDTOOL;
GRANT DEBUG ANY PROCEDURE TO EDTOOL;
GRANT DEBUG CONNECT SESSION TO EDTOOL;
GRANT DELETE ANY TABLE TO EDTOOL;
GRANT CREATE SEQUENCE TO EDTOOL;
GRANT CREATE SESSION TO EDTOOL;
GRANT CREATE SYNONYM TO EDTOOL;
GRANT CREATE TABLE TO EDTOOL;
GRANT CREATE TRIGGER TO EDTOOL;
GRANT CREATE TYPE TO EDTOOL;
GRANT CREATE USER TO EDTOOL;
GRANT CREATE VIEW TO EDTOOL;

